Solve the following problem using [Python SciPy.optimize][]. Please attach your code and
results. Specify your initial guesses of the solution. If you change
your initial guess, do you find different solutions? (**100 points**)

$$
\begin{aligned}
&\text{minimize:} && (x_1-x_2)^2 + (x_2+x_3-2)^2 + (x_4-1)^2+(x_5-1)^2 \\\\
&\text{subject to:} && x_1 + 3x_2 = 0 \\\\
&&& x_3 + x_4 - 2x_5 = 0 \\\\
&&& x_2 - x_5 = 0 \\\\
&&& -10 \leq x_i \leq 10, \~i=1,\ldots,5
\end{aligned}$$

**Note**:

1.  Please learn how to use **break points** to debug. **I will not
    address your programming questions if you have not learned how to
    debug your code.**

2.  I recommend [PyCharm][] as the IDE. If you are new to Python, you can also start with [Google Colab][] without installing anything.
    
3.  If you are on Windows, the [Anaconda][] version of Python 3 is highly recommended.


**Here are the steps to push a homework submission**:

1.  Clone the [course repo][]: First click on **Code** to get the
 Git address (e.g., the HTTPS address). Then use your IDE to clone (download) the repo using this address. 
 [PyCharm tutorial][] on using Git.

2.  You will find the homework in the **Homework** folder.

3.  For analytical problems (e.g., proofs and calculations), please use [Markdown][] to type up your answers. 
[Markdown Math][]. For Latex users, you can convert tex to markdown using [Pandoc][]. 

4. For coding problems, please submit a [Jupyter Notebook][] file with your code and final results. 
You can also add a URL to your Jupyter or Colab Notebook in README.md if you use online notebooks.

5. For each homework, please submit a single notebook file (or link) that combines the markdown solutions, 
the codes, and the computation results, and name the file according to the homework.  

6. **IMPORTANT** Please push (upload) the notebook file every time you work on the 
homework and add comments when you push, e.g., "finished problem 1, still debugging problem 2". This way I 
know you worked on your own.
 

[Python SciPy.optimize]: https://docs.scipy.org/doc/scipy/reference/tutorial/optimize.html#
[PyCharm]: https://www.jetbrains.com/pycharm/promo/?utm_source=bing&utm_medium=cpc&utm_campaign=AMER_en_US-PST%2BMST_PyCharm_Branded&utm_term=pycharm&utm_content=pycharm
[Google Colab]: https://colab.research.google.com
[Anaconda]: https://anaconda.org/anaconda/python
[course repo]: https://github.com/DesignInformaticsLab/DesignOptimization2021Fall
[PyCharm tutorial]: https://www.jetbrains.com/help/pycharm/set-up-a-git-repository.html#clone-repo
[Pandoc]: https://pandoc.org/try/
[Jupyter Notebook]: https://jupyter.org/try
[Markdown]: https://guides.github.com/features/mastering-markdown/
[Markdown Math]: http://luvxuan.top/posts/Markdown-math/

#### Import libraries first

In [43]:
from scipy import optimize
import numpy as np
import pandas as pd

In [3]:
def f(x):
    assert len(x) == 5, "There are 5 variables!"
    return (x[0]-x[1])**2 + (x[1] + x[2] - 2)**2 + (x[3] - 1)**2 + (x[4] - 1)**2

### Define Constraints 

In [4]:
def constraint1(x):
    return x[0] + 3*x[1] 

def constraint2(x):
    return x[2] + x[3] - 2*x[4] 

def constraint3(x):
    return x[1] - x[4]  

### Make dictionaries of constraints and make a tuple

In [5]:
#source consulted: https://towardsdatascience.com/optimization-with-scipy-and-application-ideas-to-machine-learning-81d39c7938b8

cons1 = {'type': 'eq', 'fun': constraint1}
cons2 = {'type': 'eq', 'fun': constraint2}
cons3 = {'type': 'eq', 'fun': constraint3}

cons = (cons1, cons2, cons3)

bounds = (-10, 10)

In [33]:
'''
initial guess of zeroes
minimize using optimize.minimize with bounds and constraints 
method used: SLSQP
same bounds for all vars
'''

#check with multiple guesses
#x0 = [0, 0, 0, 0, 0]
minimums = []
guesses = []
for i in range(10):
    x0 = np.random.rand(5)*10 - 10
    guesses.append(x0)
    minimum = optimize.minimize(fun=f, method='SLSQP', bounds=(bounds, bounds, bounds, bounds, bounds), x0=x0, constraints = cons)
    minimums.append(minimum)

minimums.append(optimize.minimize(fun=f, method='SLSQP', bounds=(bounds, bounds, bounds, bounds, bounds), x0= [0, 0, 0, 0, 0], constraints = cons))
guesses.append([0, 0, 0, 0, 0])

We can see the solutions for the guesses below: 

In [42]:

print('     -----------------Solutions--------------------- \t             ----------------------Guesses--------------')
for j in range(len(minimums)):
    print(minimums[j].x, guesses[j])

     -----------------Solutions--------------------- 	             ----------------------Guesses--------------
[-0.76743594  0.25581198  0.62792529 -0.11630133  0.25581198] [-5.44034522 -3.18998393 -6.69748374 -4.85264124 -5.79018015]
[-0.76744767  0.25581589  0.62789916 -0.11626738  0.25581589] [-5.28079942 -4.15077552 -4.30054702 -1.19137778 -5.34490343]
[-0.76743932  0.25581311  0.62791285 -0.11628663  0.25581311] [-0.12319224 -5.1931044  -7.87662892 -6.19035746 -1.64629288]
[-0.76744453  0.25581484  0.62789748 -0.11626779  0.25581484] [-9.79529312 -8.22938715 -0.59985847 -5.84433567 -3.29433568]
[-0.76744185  0.25581395  0.62790699 -0.11627908  0.25581395] [-1.36213269 -3.7187524  -1.50625939 -8.93620214 -1.04375646]
[-0.76744186  0.25581395  0.62790697 -0.11627907  0.25581395] [-0.1557076  -7.63987814 -7.61172376 -4.00905576 -0.78256392]
[-0.76744347  0.25581449  0.62790855 -0.11627957  0.25581449] [-9.73993996 -7.74999429 -4.30412685 -9.06127427 -9.69827437]
[-0.76744185  0.25581

In the above result it can be observed that the solutions are accurate to 3 decimal places for random 10 random guesses of each variable. Beyond that, the results are different based on the initial guesses. 

In [67]:
df = pd.DataFrame(columns = ['x1', 'x2', 'x3', 'x4', 'x5', 'Minimum'])
df.loc[0] = np.append(minimums[10].x, minimums[10].fun)
df.set_axis(['Solutions'], inplace=True)

### The values for each variables (x1, x2, x3, x4, and x5) that minimize the objective function f(x) are shown below (initial guess of zeros):

In [68]:
df

x1        x2        x3        x4        x5   Minimum
Solutions -0.767442  0.255814  0.627907 -0.116279  0.255814  4.093023